name: Check flake formatting
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.nix"
      - ".github/workflows/check.yml"
  push:
    paths:
      - "**.nix"
      - ".github/workflows/check.yml"
jobs:
  name: "Check flake formatting"
  check-formatting:
    uses: ./.github/workflows/prelude.yml
    secrets:
      GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    with:
      command: |
        nix-fast-build -- --skip-cached --no-nom --flake .#checks."$(nix eval --raw --impure --expr builtins.currentSystem)".treefmt
