name: Update pinned sources
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 1 * *" # 4AM on 1st of every month
    - cron: "0 4 15 * *" # 4AM on the 15th of every month
jobs:
  update:
    if: github.repository == 'notashelf/nyx'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Install Lix"
        uses: DeterminateSystems/nix-installer-action@v13
        with:
          source-url: "https://install.lix.systems/lix/lix-installer-x86_64-linux"
          diagnostic-endpoint: "" # so eelco can have more personalized self-merges? no thank you
          backtrace: "true"
          extra-conf: |
            experimental-features = nix-command flakes
            allow-import-from-derivation = false

      - name: "Update npins"
        run: |
          cd parts || exit
          nix run nixpkgs#npins update

      - name: "Commit Changes"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: GitHub Actions
          commit_message: "[CI]: update npins"
          commit_options: "--no-verify --signoff"
          push_options: "--force"
